/* Word data for Speak & Play.
 * Each category has an emoji icon, a friendly color, and a list of words.
 * Every word has:
 *   - word:  the text shown and spoken
 *   - emoji: the big picture
 *   - say:   (optional) a simpler phonetic hint used by the speech
 *            recognizer as an extra "accepted" answer for little mouths.
 * Emojis keep the whole app self-contained: no image files, no network,
 * works offline and on GitHub Pages with zero setup.
 */
const CATEGORIES = [
  {
    id: "letters",
    name: "ABC",
    icon: "🔤",
    color: "#ffb5a7",
    // "sound" is the letter's phonics sound, used in Say It ("A says ah").
    words: [
      { word: "A", emoji: "A", sound: "aah" },
      { word: "B", emoji: "B", sound: "buh" },
      { word: "C", emoji: "C", sound: "kuh" },
      { word: "D", emoji: "D", sound: "duh" },
      { word: "E", emoji: "E", sound: "eh" },
      { word: "F", emoji: "F", sound: "ffuh" },
      { word: "G", emoji: "G", sound: "guh" },
      { word: "H", emoji: "H", sound: "huh" },
      { word: "I", emoji: "I", sound: "ih" },
      { word: "J", emoji: "J", sound: "juh" },
      { word: "K", emoji: "K", sound: "kuh" },
      { word: "L", emoji: "L", sound: "luh" },
      { word: "M", emoji: "M", sound: "mmm" },
      { word: "N", emoji: "N", sound: "nnn" },
      { word: "O", emoji: "O", sound: "awh" },
      { word: "P", emoji: "P", sound: "puh" },
      { word: "Q", emoji: "Q", sound: "kwuh" },
      { word: "R", emoji: "R", sound: "ruh" },
      { word: "S", emoji: "S", sound: "sss" },
      { word: "T", emoji: "T", sound: "tuh" },
      { word: "U", emoji: "U", sound: "uh" },
      { word: "V", emoji: "V", sound: "vuh" },
      { word: "W", emoji: "W", sound: "wuh" },
      { word: "X", emoji: "X", sound: "ks" },
      { word: "Y", emoji: "Y", sound: "yuh" },
      { word: "Z", emoji: "Z", sound: "zzz" },
    ],
  },
  {
    id: "numbers",
    name: "123",
    icon: "🔢",
    color: "#b8e0ff",
    words: [
      { word: "one", emoji: "1️⃣" },
      { word: "two", emoji: "2️⃣" },
      { word: "three", emoji: "3️⃣" },
      { word: "four", emoji: "4️⃣" },
      { word: "five", emoji: "5️⃣" },
      { word: "six", emoji: "6️⃣" },
      { word: "seven", emoji: "7️⃣" },
      { word: "eight", emoji: "8️⃣" },
      { word: "nine", emoji: "9️⃣" },
      { word: "ten", emoji: "🔟" },
    ],
  },
  {
    id: "counting",
    name: "Counting",
    icon: "🧮",
    color: "#a0e7d2",
    // "count" copies of "item" are drawn so kids can count real things
    // and say how many. Kept to 1-5 so the group fits nicely.
    words: [
      { word: "one", count: 1, item: "🍎" },
      { word: "two", count: 2, item: "⚽" },
      { word: "three", count: 3, item: "🐟" },
      { word: "four", count: 4, item: "⭐" },
      { word: "five", count: 5, item: "🦆" },
    ],
  },
  {
    id: "animals",
    name: "Animals",
    icon: "🐶",
    color: "#ffb3c1",
    words: [
      { word: "dog", emoji: "🐶" },
      { word: "cat", emoji: "🐱" },
      { word: "cow", emoji: "🐮" },
      { word: "pig", emoji: "🐷" },
      { word: "duck", emoji: "🦆" },
      { word: "fish", emoji: "🐟" },
      { word: "bird", emoji: "🐦" },
      { word: "bear", emoji: "🐻" },
      { word: "frog", emoji: "🐸" },
      { word: "lion", emoji: "🦁" },
      { word: "horse", emoji: "🐴" },
      { word: "sheep", emoji: "🐑" },
      { word: "bee", emoji: "🐝" },
      { word: "monkey", emoji: "🐵" },
    ],
  },
  {
    id: "food",
    name: "Food",
    icon: "🍎",
    color: "#ffd6a5",
    words: [
      { word: "apple", emoji: "🍎" },
      { word: "banana", emoji: "🍌" },
      { word: "milk", emoji: "🥛" },
      { word: "egg", emoji: "🥚" },
      { word: "bread", emoji: "🍞" },
      { word: "cookie", emoji: "🍪" },
      { word: "cheese", emoji: "🧀" },
      { word: "grapes", emoji: "🍇" },
      { word: "carrot", emoji: "🥕" },
      { word: "corn", emoji: "🌽" },
      { word: "cake", emoji: "🍰" },
      { word: "pizza", emoji: "🍕" },
      { word: "water", emoji: "💧" },
      { word: "juice", emoji: "🧃" },
    ],
  },
  {
    id: "body",
    name: "My Body",
    icon: "👀",
    color: "#bdb2ff",
    words: [
      { word: "eye", emoji: "👁️" },
      { word: "ear", emoji: "👂" },
      { word: "nose", emoji: "👃" },
      { word: "mouth", emoji: "👄" },
      { word: "hand", emoji: "✋" },
      { word: "foot", emoji: "🦶" },
      { word: "hair", emoji: "💇" },
      { word: "tooth", emoji: "🦷" },
      { word: "tongue", emoji: "👅" },
    ],
  },
  {
    id: "colors",
    name: "Colors",
    icon: "🌈",
    color: "#a0e7a0",
    words: [
      { word: "red", emoji: "🔴" },
      { word: "blue", emoji: "🔵" },
      { word: "green", emoji: "🟢" },
      { word: "yellow", emoji: "🟡" },
      { word: "orange", emoji: "🟠" },
      { word: "purple", emoji: "🟣" },
      { word: "pink", emoji: "🌸" },
      { word: "brown", emoji: "🟤" },
      { word: "black", emoji: "⚫" },
      { word: "white", emoji: "⚪" },
    ],
  },
  {
    id: "vehicles",
    name: "Things That Go",
    icon: "🚗",
    color: "#9bf6ff",
    words: [
      { word: "car", emoji: "🚗" },
      { word: "bus", emoji: "🚌" },
      { word: "truck", emoji: "🚚" },
      { word: "train", emoji: "🚆" },
      { word: "plane", emoji: "✈️" },
      { word: "boat", emoji: "⛵" },
      { word: "bike", emoji: "🚲" },
      { word: "rocket", emoji: "🚀" },
      { word: "digger", emoji: "🚜" },
    ],
  },
  {
    id: "actions",
    name: "Actions",
    icon: "🏃",
    color: "#fdffb6",
    words: [
      { word: "run", emoji: "🏃" },
      { word: "jump", emoji: "🤸" },
      { word: "eat", emoji: "😋" },
      { word: "sleep", emoji: "😴" },
      { word: "drink", emoji: "🥤" },
      { word: "clap", emoji: "👏" },
      { word: "wave", emoji: "👋" },
      { word: "dance", emoji: "💃" },
      { word: "sit", emoji: "🪑" },
      { word: "wash", emoji: "🧼" },
    ],
  },
  {
    id: "nature",
    name: "Outside",
    icon: "🌳",
    color: "#caffbf",
    words: [
      { word: "sun", emoji: "☀️" },
      { word: "moon", emoji: "🌙" },
      { word: "star", emoji: "⭐" },
      { word: "tree", emoji: "🌳" },
      { word: "flower", emoji: "🌼" },
      { word: "rain", emoji: "🌧️" },
      { word: "snow", emoji: "❄️" },
      { word: "cloud", emoji: "☁️" },
      { word: "leaf", emoji: "🍃" },
    ],
  },
  {
    id: "toys",
    name: "Toys & Play",
    icon: "🧸",
    color: "#ffc6ff",
    words: [
      { word: "ball", emoji: "⚽" },
      { word: "teddy", emoji: "🧸" },
      { word: "block", emoji: "🧱" },
      { word: "drum", emoji: "🥁" },
      { word: "book", emoji: "📖" },
      { word: "balloon", emoji: "🎈" },
      { word: "bubble", emoji: "🫧" },
      { word: "kite", emoji: "🪁" },
    ],
  },
];
