/* Word data for Speak & Play.
 * Each category has an emoji icon, a friendly color, and a list of words.
 * Every word has:
 *   - word:  the text shown and spoken
 *   - emoji: the big picture
 *   - say:   (optional) a simpler phonetic hint used by the speech
 *            recognizer as an extra "accepted" answer for little mouths.
 * Emojis keep the whole app self-contained: no image files, no network,
 * works offline and on GitHub Pages with zero setup.
 */
const CATEGORIES = [
  {
    id: "animals",
    name: "Animals",
    icon: "🐶",
    color: "#ffb3c1",
    words: [
      { word: "dog", emoji: "🐶" },
      { word: "cat", emoji: "🐱" },
      { word: "cow", emoji: "🐮" },
      { word: "pig", emoji: "🐷" },
      { word: "duck", emoji: "🦆" },
      { word: "fish", emoji: "🐟" },
      { word: "bird", emoji: "🐦" },
      { word: "bear", emoji: "🐻" },
      { word: "frog", emoji: "🐸" },
      { word: "lion", emoji: "🦁" },
      { word: "horse", emoji: "🐴" },
      { word: "sheep", emoji: "🐑" },
      { word: "bee", emoji: "🐝" },
      { word: "monkey", emoji: "🐵" },
    ],
  },
  {
    id: "food",
    name: "Food",
    icon: "🍎",
    color: "#ffd6a5",
    words: [
      { word: "apple", emoji: "🍎" },
      { word: "banana", emoji: "🍌" },
      { word: "milk", emoji: "🥛" },
      { word: "egg", emoji: "🥚" },
      { word: "bread", emoji: "🍞" },
      { word: "cookie", emoji: "🍪" },
      { word: "cheese", emoji: "🧀" },
      { word: "grapes", emoji: "🍇" },
      { word: "carrot", emoji: "🥕" },
      { word: "corn", emoji: "🌽" },
      { word: "cake", emoji: "🍰" },
      { word: "pizza", emoji: "🍕" },
      { word: "water", emoji: "💧" },
      { word: "juice", emoji: "🧃" },
    ],
  },
  {
    id: "body",
    name: "My Body",
    icon: "👀",
    color: "#bdb2ff",
    words: [
      { word: "eye", emoji: "👁️" },
      { word: "ear", emoji: "👂" },
      { word: "nose", emoji: "👃" },
      { word: "mouth", emoji: "👄" },
      { word: "hand", emoji: "✋" },
      { word: "foot", emoji: "🦶" },
      { word: "hair", emoji: "💇" },
      { word: "tooth", emoji: "🦷" },
      { word: "tongue", emoji: "👅" },
    ],
  },
  {
    id: "colors",
    name: "Colors",
    icon: "🌈",
    color: "#a0e7a0",
    words: [
      { word: "red", emoji: "🔴" },
      { word: "blue", emoji: "🔵" },
      { word: "green", emoji: "🟢" },
      { word: "yellow", emoji: "🟡" },
      { word: "orange", emoji: "🟠" },
      { word: "purple", emoji: "🟣" },
      { word: "pink", emoji: "🌸" },
      { word: "brown", emoji: "🟤" },
      { word: "black", emoji: "⚫" },
      { word: "white", emoji: "⚪" },
    ],
  },
  {
    id: "vehicles",
    name: "Things That Go",
    icon: "🚗",
    color: "#9bf6ff",
    words: [
      { word: "car", emoji: "🚗" },
      { word: "bus", emoji: "🚌" },
      { word: "truck", emoji: "🚚" },
      { word: "train", emoji: "🚆" },
      { word: "plane", emoji: "✈️" },
      { word: "boat", emoji: "⛵" },
      { word: "bike", emoji: "🚲" },
      { word: "rocket", emoji: "🚀" },
      { word: "digger", emoji: "🚜" },
    ],
  },
  {
    id: "actions",
    name: "Actions",
    icon: "🏃",
    color: "#fdffb6",
    words: [
      { word: "run", emoji: "🏃" },
      { word: "jump", emoji: "🤸" },
      { word: "eat", emoji: "😋" },
      { word: "sleep", emoji: "😴" },
      { word: "drink", emoji: "🥤" },
      { word: "clap", emoji: "👏" },
      { word: "wave", emoji: "👋" },
      { word: "dance", emoji: "💃" },
      { word: "sit", emoji: "🪑" },
      { word: "wash", emoji: "🧼" },
    ],
  },
  {
    id: "nature",
    name: "Outside",
    icon: "🌳",
    color: "#caffbf",
    words: [
      { word: "sun", emoji: "☀️" },
      { word: "moon", emoji: "🌙" },
      { word: "star", emoji: "⭐" },
      { word: "tree", emoji: "🌳" },
      { word: "flower", emoji: "🌼" },
      { word: "rain", emoji: "🌧️" },
      { word: "snow", emoji: "❄️" },
      { word: "cloud", emoji: "☁️" },
      { word: "leaf", emoji: "🍃" },
    ],
  },
  {
    id: "toys",
    name: "Toys & Play",
    icon: "🧸",
    color: "#ffc6ff",
    words: [
      { word: "ball", emoji: "⚽" },
      { word: "teddy", emoji: "🧸" },
      { word: "block", emoji: "🧱" },
      { word: "drum", emoji: "🥁" },
      { word: "book", emoji: "📖" },
      { word: "balloon", emoji: "🎈" },
      { word: "bubble", emoji: "🫧" },
      { word: "kite", emoji: "🪁" },
    ],
  },
];
